### ISSUE TITLE
Error: Couldn't Get Media Stream

### ISSUE THREAD

**Issue by nab-os** [Charles-Schleich/WebRTC-in-Rust#2]
When starting a new Session I get this error in the console:
Uncaught (in promise) Error: Couldn't Get Media Stream

A have a working camera and yet it doesn't even ask access to it.
I tried with Firefox as well as Chromium

Do you have any idea where it could come from ?

**Comment by Charles-Schleich** [comment]
So when trying to get media streams, its possible that media capture from  url’s without certificates has not been enabled. So most browsers will immediately reject access to camera and mic.

On Chrome, navigate to `chrome://flags` in the URL bar and adding your server IP and port under `Insecure origins treated as secure`.
it should look something like this `http://0.0.0.0:9000,http://192.168.178.35:9000`, with the `192` address being the IP address of the server if you are trying to connect from a device outside from where the server is hosted (i.e. a phone/other laptop). 

On Firefox navigate to `about:config` in the URL bar, and change `media.devices.insecure.enabled` to `true` and `media.getuser.media.insecure.enabled` to `true`
 
If you plan on using your smartphone browser as your second WebRTC client, you will need to do the same, and this is easier to do on chrome mobile connected to a pc with a cable and connecting to the mobile chrome instance via `chrome://inspect/#devices` on pc. 
You can see the console of the mobile device as well, its super useful.

Let me know if this helps.

**Comment by nab-os** [comment]
It works now !
Thank you !
